server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: image_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: java.util,com.example.imageservice

aws:
  s3:
    bucket: localstack
    region: us-east-1
    access-key: access-key
    secret-key: secret-key
    endpoint: http://localstack:4566

cloud:
  aws:
    s3:
      endpoint: http://localstack:4566
jwt:
  secret: "8c9d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d8c9d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d" # ?????? ????????? ? Auth Service
logging:
  level:
    io.jsonwebtoken: DEBUG
    org.springframework.security: DEBUG